apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: fleet-allow-traefik
spec:
  podSelector:
    matchLabels:
      app: fleet-service
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
    - from:
        - podSelector:
            matchLabels:
              app: fleet-service