apiVersion: v1
kind: Service
metadata:
  name: fleet-service
  namespace: craftcloud-system
spec:
  selector:
    app: fleet-service
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http