apiVersion: k8s.keycloak.org/v2beta1
kind: Keycloak
metadata:
  name: keycloak
  namespace: craftcloud-system
spec:
  instances: 1
  db:
    vendor: postgres
    host: craftcloud-db-rw
    database: keycloak
    usernameSecret:
      name: craftcloud-db-app
      key: username
    passwordSecret:
      name: craftcloud-db-app
      key: password
  additionalOptions:
    - name: proxy
      value: edge
    - name: proxy-headers
      value: xforwarded
  http:
    httpEnabled: true
  hostname:
    hostname: sso.127.0.0.1.nip.io
    strict: false
    strictBackchannel: false