apiVersion: k8s.keycloak.org/v2beta1
kind: KeycloakRealmImport
metadata:
  name: craftcloud-realm-import
  namespace: craftcloud-system
spec:
  keycloakCRName: keycloak
  realm:
    realm: creaftcloud
    enabled: true