creation_rules:
  - path_regex: 'k8s(/|\\)overlays(/|\\)dev(/|\\).*\.(sops|plain)\.yaml$'
    age: age1xkwx4z6rzmf95xvqnan69agjyvt0lrh0305gzh6p5anndfaee9mqur9933
  - path_regex: 'k8s(/|\\)overlays(/|\\)prod(/|\\).*\.sops\.yaml$'
    age: <your-prod-age-public-key>