# fabfile.py
import json
from fabric import task
from patch import Connection

# Load the dynamic IPs generated by your provisioning script
with open('cluster_ips.json', 'r') as f:
    IPS = json.load(f)

CLUSTER_TOKEN = "AgonesCloudLabSecureToken123"

@task
def setup_cluster(c):
    # 1. Setup Control Plane
    master_ip = IPS['master']
    print(f"Bootstrapping Control Plane at {master_ip}...")
    master = Connection(host=master_ip, user="ubuntu") # Default FABRIC user
    
    master.put('./infra/bootstrap', '/tmp')
    master.run('chmod +x /tmp/booststrap/*.sh')
    master.run(f'sudo /tmp/bootstrap/setup_control_plane.sh {CLUSTER_TOKEN}')

    # 2. Setup Workers
    for worker_ip in IPS['workers']:
        print(f"Bootstrapping Worker at {worker_ip}...")
        worker = Connection(host=worker_ip, user="ubuntu")
        
        worker.put('./infra/bootstrap', '/tmp')
        worker.run('chmod +x /tmp/bootstrap/*.sh')
        
        # Pass BOTH the token and the master_ip to the worker script
        worker.run(f'sudo /tmp/bootstrap/setup_worker.sh {CLUSTER_TOKEN} {master_ip}')

@task
def deploy_app(c):
    """Uploads the project and runs Skaffold on the Control Plane"""
    # Load the dynamic IP
    with open('cluster_ips.json', 'r') as f:
        master_ip = json.load(f)['master']
    
    print(f"Connecting to Control Plane ({master_ip}) to deploy app...")
    master = Connection(host=master_ip, user="ubuntu")
    
    # 1. Create a directory for your project on the server
    master.run('mkdir -p ~/my-game-platform')
    
    # 2. Upload your entire project directory using rsync (much faster than standard put for whole folders)
    # Note: Requires rsync installed locally and on the server
    print("Uploading project files...")
    master.local(f'rsync -avz --exclude=".git" --exclude="node_modules" ./ {master.user}@{master.host}:~/my-game-platform')

    # 3. Execute Skaffold using the k8s/overlays/prod environment
    print("Running Skaffold build and deploy...")
    with master.cd('~/my-game-platform'):
        # Ensure kubeconfig is loaded so Skaffold can talk to K3s
        master.run('export KUBECONFIG=/etc/rancher/k3s/k3s.yaml && skaffold run -p prod')
        
    print("🚀 Application successfully deployed!")