# fabfile.py
import json
import os
from fabric import Connection, task

# Load the dynamic IPs generated by your provisioning script
with open('cluster_ips.json', 'r') as f:
    IPS = json.load(f)

CLUSTER_TOKEN = "AgonesCloudLabSecureToken123" # <-- SECURITY RISK REMOVVE WITH EV

# --- FABRIC SSH CONFIGURATION ---
BASTION_USER = "jm1029804_0000480603" # <-- REPLACE THIS
BASTION_HOST = "bastion.fabric-testbed.net"
BASTION_KEY = "/home/fabric/.ssh/fabric-bastion-key"
SLIVER_KEY = "/home/fabric/.ssh/slice_key"

# Create the Bastion jump host connection
bastion = Connection(
    host=BASTION_HOST, 
    user=BASTION_USER, 
    connect_kwargs={"key_filename": BASTION_KEY}
)

def get_node_connection(ip):
    """Helper function to create a proxied connection to a node"""
    return Connection(
        host=ip,
        user="ubuntu",
        gateway=bastion, # This tells Python Fabric to jump through the Bastion!
        connect_kwargs={"key_filename": SLIVER_KEY}
    )

@task
def setup_cluster(c):
    
    print("Packaging bootstrap scipts...")
    c.run('tar -czf bootstrap.tar.gz -C ./infra bootstrap')
    
    # 1. Setup Control Plane
    master_ip = IPS['master']
    
    print(f"Re-configuring Control Plane at {master_ip} for IPv6...")
    master = get_node_connection(master_ip)

    master.put('bootstrap.tar.gz', '/tmp/bootstrap.tar.gz')
    master.run('tar -xzf /tmp/bootstrap.tar.gz -C /tmp')
    
    master.run('chmod +x /tmp/bootstrap/*.sh')
    master.run(f'sudo /tmp/bootstrap/setup_control_plane.sh {CLUSTER_TOKEN} {master_ip}')

    # 2. Setup Workers
    for worker_ip in IPS['workers']:
        print(f"Bootstrapping Worker at {worker_ip}...")
        worker = get_node_connection(worker_ip)
        
        worker.put('bootstrap.tar.gz', '/tmp/bootstrap.tar.gz')
        worker.run('tar -xzf /tmp/bootstrap.tar.gz -C /tmp')
        
        worker.run('chmod +x /tmp/bootstrap/*.sh')
        worker.run(f'sudo /tmp/bootstrap/setup_worker.sh {CLUSTER_TOKEN} {master_ip} {worker_ip}')
    
    c.run('rm bootstrap.tar.gz')

@task
def deploy_app(c, repo_url):
    """Clones a Git repo onto the Control Plane and deploys it via Skaffold"""
    # Load the dynamic IP
    with open('cluster_ips.json', 'r') as f:
        master_ip = json.load(f)['master']
    
    print(f"Connecting to Control Plane ({master_ip}) to deploy app...")
    master = get_node_connection(master_ip)
    
    repo_name = repo_url.split('/'[-1].replace('.git', ''))
    target_dir = f"~/{repo_name}"
    
    print(f"Cloning repository from {repo_url}...")
    master.run('sudo apt-get install -y git', hid=True)
    
    master.run(f'rm -rf {target_dir}')
    master.run(f'git clone {repo_dir} {target_dir}')
    
    # 3. Execute Skaffold using the k8s/overlays/prod environment
    print("Running Skaffold build and deploy...")
    with master.cd(target_dir):
        # Ensure kubeconfig is loaded so Skaffold can talk to K3s
        master.run('export KUBECONFIG=/etc/rancher/k3s/k3s.yaml && skaffold run -p prod')
        
    print("🚀 Application successfully deployed from Git!")