apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: craftcloud

requires:
  - path: services/identity-billing-service/skaffold.yaml
  - path: services/fleet-manager/skaffold.yaml
  - path: services/telemetry-service/skaffold.yaml
  - path: apps/webui/skaffold.yaml
  - path: workers/mod-syncer/skaffold.yaml
  - path: workers/ai-worker/skaffold.yaml
  - path: workers/payment-worker/skaffold.yaml
  - path: sidecar/skaffold.yaml

build:
  tagPolicy:
    gitCommit: {}
        
profiles:
  - name: dev
    activation:
      - command: dev
    manifests:
      rawYaml:
        - deployments/k8s/base/namespace.yaml
      kustomize:
        paths:
          - deployments/k8s/overlays/local-dev
        buildArgs:
          - "--enable-alpha-plugins"
          - "--enable-exec"
          - "--enable-helm"
          - "--load-restrictor=LoadRestrictionsNone"
    deploy:
      kubectl: {}

  - name: prod
    build:
      local:
        push: true
    manifests:
      kustomize:
        paths:
          - deployments/k8s/overlays/prod
        buildArgs:
          - "--enable-alpha-plugins"
    deploy:
      kubectl: {}

portForward:
  - resourceType: service
    resourceName: dashboard
    namespace: craftcloud-system
    port: 80
    address: 127.0.0.1
    localPort: 8080
  - resourceType: service
    resourceName: identity-service
    namespace: craftcloud-system
    port: 5000
    localPort: 5000
  - resourceType: service
    resourceName: fleet-service
    namespace: craftcloud-system
    port: 5000
    localPort: 5001
  - resourceType: service
    resourceName: telemetry-service
    namespace: craftcloud-system
    port: 5000
    localPort: 5002