apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: craftcloud

build:
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: manager-api-image
      context: backend
      docker:
        dockerfile: Dockerfile
        
    - image: dashboard-image
      context: webui
      docker:
        dockerfile: Dockerfile
        
    - image: mod-syncer-image
      context: mod-syncer
      docker:
        dockerfile: Dockerfile
        
    - image: ai-rag-worker-image
      context: worker
      docker:
        dockerfile: Dockerfile
        
    - image: valheim-sidecar-image
      context: sidecar
      docker:
        dockerfile: Dockerfile

profiles:
  - name: dev
    activation:
      - command: dev
    build:
      local:
        push: false
      artifacts:
       - image: manager-api-image
         context: backend
         docker:
           dockerfile: Dockerfile
           target: dev
         sync:
           manual:
             - src: 'app/**/*.py'
               dest: /app

       - image: dashboard-image
         context: webui
         docker:
           target: dev
           dockerfile: Dockerfile
         sync:
           manual:
             - src: 'src/**/*'
               dest: /app
             - src: 'index.html'
               dest: /app
    manifests:
      kustomize:
        paths:
          - k8s/overlays/dev
    deploy:
      kubectl: {}

  - name: prod
    manifests:
      kustomize:
        paths:
          - k8s/overlays/prod
    deploy:
      kubectl: {}

portForward:
  - resourceType: service
    resourceName: dashboard
    namespace: craftcloud-system
    port: 80
    address: 127.0.0.1
    localPort: 8080
  - resourceType: service
    resourceName: manager-api
    namespace: craftcloud-system
    port: 5000
    localPort: 5000