apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: ai-worker

build:
  artifacts:
    - image: ai-rag-worker-image
      context: .

profiles:
  - name: dev
    activation:
      - command: dev
    build:
      local:
        push: false