apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: identity-billing-service

build:
  artifacts:
    - image: identity-api-image
      context: .

profiles:
  - name: dev
    activation:
      - command: dev
    build:
      local:
        push: false
        useDockerCLI: true
      artifacts:
        - image: identity-api-image
          context: .
          docker:
            target: dev
          sync:
            manual:
              - src: 'app/**/*.py'
                dest: /app