apiVersion: v1
kind: Namespace
metadata:
  name: valheim-workloads
  labels:
    purpose: game-servers
---
apiVersion: v1
kind: Namespace
metadata:
  name: craftcloud-system
  labels:
    purpose: platform-infrastructure