apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: craftcloud-system

generators:
  - ksops-generator.yaml

helmCharts:
  - name: postgresql
    repo: oci://registry-1.docker.io/bitnamicharts
    version: 18.5.24
    releaseName: postgres
    namespace: craftcloud-system
    valuesFile: values/postgres-values.yaml