apiVersion: ENC[AES256_GCM,data:Dh0=,iv:FrhP2ngVfyymhetIdqpuSXhDXm6DpKFn91LTZd9xANk=,tag:BodB3glUukVEHuW/0nrOZw==,type:str]
kind: ENC[AES256_GCM,data:6IbH0CG7,iv:pYxNx1ertY89rlzhu9Val3JY8pSWoYIjIU6qjBhNRZE=,tag:AyDmD9bA+BLXodTYQpGdXw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:r8u8aTR35xFhvggm9w==,iv:utF2QGxr3qr+o/RWDdn9I1mZyOUbQTbJ9XOmwiDJjyE=,tag:MLrK5VbxF5FPk6MOCmVyiA==,type:str]
type: ENC[AES256_GCM,data:HuhbGTGs,iv:oW4Agtpb4iBZGFxvOs40CmGBmU6oh4b8zZVWT55j3I0=,tag:dGdPdqYzi8PSBIUtD+x3MA==,type:str]
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:gn5wjqjDj4GtdsG0dvipWr/15+itTSimYgZA9I7o5+y5YhDQsmk2/1SReb3Jfjqwdq+Ngxv/eQXSe0w5hzXnag==,iv:TFRsyYneruYhn66DCubTc+BCPHmDXMvpehbCfKGL/rI=,tag:6XFgWOVuGL9jxQCfJNXREQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:dN7fkLYITMvW8DJiE4laa9wGZZY7ge6aUcUu9YwtXybpH6Ra2YZLZm+G9uyVGU6zGY8Iblri5y7cJbztx119oHqx5p5llwupFwXUpv63,iv:xPQ7VJySRF9Tu90Bvw93HV8sUn1pixRvnsLNwwlk/NU=,tag:Ot0B2ElY1rblPPx/6Bp1Tg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVjdFSmNSMElwbWR1SXdJ
            NU85L1ZLZEVyTWhJeWsrQndoTVNkYU9xeXl3CjR2Y0ZXcmNTSVBLSGlzTENnS2hW
            Wm9zYXNmVkxsNXJpV1pweFFzelRQMk0KLS0tIGNlRzlRcmNnbHhTTnhvQWo4aXM4
            SUlvNXRGMi9SSUcwMTZQVHBOTy8rMkUKkw+59yL/ysI8ut91aXx41C9Rjw6UtJ0J
            Re8J3J+XtefWYl0/loiWZv3umX0YDgb7D99gWGV6J5lYViBuZhBRWw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yngf5ztpu6g6da96xdlheheyv5pwuax2g7yale5d4tvwd6y02c7sc8gfm6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRaHM2cExxdkduZGJycTBP
            UG1LQTJWTHVJWDc5eFV4ZmpReUlqaVVsNDJNCk1VdnNkMWEwaEpScTFCNEUrY2VV
            TlRvV3h5aGY1Q0RhMDJQb2FKT0ZRL3MKLS0tIFQ5akoyVWtjVkxpY2ZaejBSeEYx
            Q1NYR0diUmFzUzJsR1E4UXYrN1NaTVUKJPhEaQVYlWZTyLpPNlamJzJbtJrRIFu1
            2qMXvvmisNEZcEqgYBm+sLYMLYAERSoFlrK7GuX1BBVtH3BEFMmdgw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12r0mh7h98zrn7m0zrzwxm75wr3terzkf6q58nqg64tcul5eyfg0qmgt5lk
    lastmodified: "2026-05-13T19:01:20Z"
    mac: ENC[AES256_GCM,data:KDfeVeX23VogNYUHo34fvRT7n7+mBbn0s6OAI8LHeMR+9Z6zFfrjf7ojxUEa76skb+XaXyIyUWCjjUn2+LJpyLd67JCe00hnW+3oKFCNbW+o/UNElr4KsGEh4xw3KKUWPxrF1MZ3pERzrIHxaRTihLu9eDaYJOPkIvLDU2aiOvM=,iv:UDRVEM2HGZn24SqfPSs2gtoEGVHQK2PDENJO3U+Qllo=,tag:SqGWPTyPhSHQ383VfctSYQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.7.3
