apiVersion: ENC[AES256_GCM,data:tLw=,iv:KWvroRF3lvjIRS6m8XI5R62KOYvbXVAg/QTWAq+pcw0=,tag:bBYi2KCnH9Hw/FRd5sLIxw==,type:str]
kind: ENC[AES256_GCM,data:X7oOfiz2,iv:+LFRQVi0sFwtUhevHZlDBN2VYOY+jz8RLZ9qq8rpshQ=,tag:YV2JQnwSfORI7P38tJUw4w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:PiFhvNNzA0+xXr9Qp6+X+Q==,iv:VWrL1wUjMdKnDGSzhGFqVyMUNAen+GqxI0uyxUgP+Wk=,tag:wEydInOMHvZkbCat+KDK8w==,type:str]
type: ENC[AES256_GCM,data:GjdoJogH,iv:FXEli1Khm9ZtdYbpZtEIc7L5lgYC7fE4QK7+GvQ7Ocs=,tag:OI3SnaJKZHFbLSAU8sydBQ==,type:str]
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:uTUCkD2Az+itFuxU5N5zVE26CFwGMNrWg+ejHIidIGhrDJfFX2y6hgHeYVyxAKYkuIC9Kt/8MFIZAKmslvs8iA==,iv:546dbNA8utNCP0/YbC6H8FABk650FY7IRsAvNLutoJw=,tag:EP35vO1L6s0948oQs9HDAA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:ISz4te8/wBXL+T1NpeIwZczbjloa4D3puxXuPXTe8MU5T7Pgb3acPWUytVVdfCGz0sBwKmwVOZpV0fPjg+GzN08SRhaDNo1ybbVK54Z1,iv:Tzt7DIKFk4YyIHXTMMf3rgFL2gr6PrnYLUxCF5CYsww=,tag:r9vnA4AVbrmk5+Ha5lEVNg==,type:str]
    SIDECAR_API_KEY: ENC[AES256_GCM,data:5Z6z0x4xFUBLaUwPrahCxf4=,iv:r0Ab/ZqPv3N2s7k7siFHZ0Dx1PtIVt0XxI8dvlTkKlg=,tag:NyJsFB6eieuEWDHQZC9yCA==,type:str]
    INTERNAL_API_KEY: ENC[AES256_GCM,data:Qr8VRgqx/NyQo2Nz07li3iP9zFhWbYzpRIwTDvMEH5iVx22QkbQzORbnASt2bm8IuyRLc797s2qpbsrixGqKUA==,iv:BUqlU6ZuYGElJ3gFJgC0ggrZZk/d075bO4Kvb/2vkqk=,tag:Ee4p1LGXCrTI3MbzHmSjzQ==,type:str]
    STRIPE_WEBHOOK_SECRET: ENC[AES256_GCM,data:PTmOVgCqLcHG,iv:pfeHBOoMUTJ5XKgBk/CSE+c4knv7Hf53M9VBQlsCUeE=,tag:L0GHe4tK2oCbua0OysUmQw==,type:str]
    PAYPAL_CLIENT_ID: ENC[AES256_GCM,data:vE/o,iv:y75WEknLDR9zmqKjhmDkhnoDLLlyuMFGtnDXUPZl1TE=,tag:ezngbh8JkwM47Rwt7F5dmw==,type:str]
    PAYPAL_CLIENT_SECRET: ENC[AES256_GCM,data:4cV5,iv:WvnpcuV4nE5DPnym1Xoarze49+OC0NCLcahgrpNXze8=,tag:eC9Q//Zt7RFqfk83TqFdMw==,type:str]
    PAYPAL_WEBHOOK_ID: ENC[AES256_GCM,data:41DK,iv:Xq81mJ+nPnC+LcozAkDNK/UVhOiQecDdzZvY+ma9a28=,tag:4oxzVZykyHgEF5lT5YZPzQ==,type:str]
    STRIPE_SECRET_KEY: ENC[AES256_GCM,data:dDGRiQPimdQjFXu8BJNMrOV6Yt1KLY9r0bbiMn2Um+HBcJo=,iv:2VI5muwQ5DDlAG7g04NANtMtjQnob7kvJaB19XiRuq0=,tag:6+WJFjOwXgMjG6L0HIK6cA==,type:str]
    OIDC_ISSUER_URL: ENC[AES256_GCM,data:b9GLT96sEWmYMQEw1ob3OKRYEuj/oHtkWFdiuB3U48VDi07d/avPHUvtXuDWolceoS4r7iM4Zf269d3xnAAyywf6XDOEWPu8glB0ECS16o574w==,iv:+mQ40IY1YSDzum+1AEwVtaINa6Y94vTwT+OL3ErpMxY=,tag:Sbe0C9ObUsdCAZPZjlYfoQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJOUtGUi9aU3dUZHJXVytm
            U3NNVE5qNnBnZWEyVzg1TnlHWDJacncxb3l3CnVWVS9lbVpYbWRtUXVKQjR4Mmhn
            MklWc3hMMG9meFptLzhKVXVsN0NYR28KLS0tIFhTbEMwRVZWakpQYnp6bFJmUXRC
            NUFzNFBkNFlNS3NGTHMyZWpXREpOdWcK6BR3R0jamd7QnH1BtxoQx6skQl2H//zJ
            p5YoaMfIQftY+eJZpkkbW+dWK/wgc+EPQy4bPH4jl6zcUoTtRoT9cg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yngf5ztpu6g6da96xdlheheyv5pwuax2g7yale5d4tvwd6y02c7sc8gfm6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZSDRIejl2bThOaTU3S0Nx
            dy9rOWZyOWxDYjRxRmZLbWsvYUttS1BPNFRNClM0MVVucHdUaHpOTDFhQlZKakxL
            VkxMU0ZQNVFpRWZWYTFBV3hoVmNoYVUKLS0tIEFya3V1VGFrdjZ3T01wOHBZUGE1
            TE5US0xCWU5rcGN4SUc1S3p1aG83TG8KKPIv6xcxnfJ6/EHEDfuO9cjy42RcyHCO
            oTHAx5wA/zWlKrrDuwTyYm6E7hDUpeghu54W3V7pT+uolL2rVwsjvw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12r0mh7h98zrn7m0zrzwxm75wr3terzkf6q58nqg64tcul5eyfg0qmgt5lk
    lastmodified: "2026-07-13T20:56:15Z"
    mac: ENC[AES256_GCM,data:B+EB7nyXrbPV6+GZz6PSQLivAdKxI5/wltS6kxQvl7Cs68sPHzMMC1EhKS9k+7yVnwOgXXJxTC5hk4VBta4/dE8yAwx0U0qLyi0/SKeR3HR2ARgmVfEmmrImOAdslucxO+AKoTeT1f912+8MgAc1rTRSiFsdSgENrPOUqdHYFWQ=,iv:3pljI1pirqeT+X4/xBGSSZhjfSfIhpw8GWe6mfMyA64=,tag:nXerFz6ZcvTrncBOInu4lg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.7.3
