apiVersion: ENC[AES256_GCM,data:+XE=,iv:1fHcEVd8v7PLjQJ4ZMvGQwWWM1pT2Av7A26+S7zEEiY=,tag:MksFNczQyBudW0mDY6Nnsw==,type:str]
kind: ENC[AES256_GCM,data:10DnGUfd,iv:4gekO15x5CHxaVw3DXm58Nwf+9rV89X/7vzTk9o8efg=,tag:92LR4XKI/vILp/Egch7B7w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:IGaOInacKL6nz4w3CIY=,iv:9JT62MCOjAXWOw1+v8Q5EZx544JW8JA+imEu941BvJE=,tag:SSzPX8CcLAQrSGpi2u1k4A==,type:str]
    namespace: ENC[AES256_GCM,data:eBBhL9zOPoplyHCYxfYHQ1Q=,iv:BtEUAoolmTEMMHx+b+IPaHzBTP9HkaUcRZXmFFalz5I=,tag:9opg4vlVGLTDFbEpDlQ5lQ==,type:str]
stringData:
    API_KEY: ENC[AES256_GCM,data:yo4INzZ78yxI3Bo9l2CWPS02kzJtDmZbpHCi,iv:VKtCRjn18XtMMfzue6xTbRtSmIsev2sTqe3bPctuR5g=,tag:US4ZkgVUKVmiKLWividypQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWd2dTUkUrSlhweUpWVCsz
            Sjg5N05zYWpoZW5XTkptaWtNNHUvVFhnTlRRCmM3eXdWTTNKWW5taWQxOU9YU2xu
            RnJNWEdseDIvdE82SGwxVnYrNG8ybFEKLS0tIEhJb1lmUFY0RElzWU1BVFNoWk45
            dytFbXM5bktWZTlXT3ZQcWJFdk9hOWMKSvNiHe4KjHPwFU5+tZdlfgqIOeE3fVBa
            95u6eaIbCFiqCnS0ZQmC5ygwRMqWFtPLqR6m+iArp43Q88a2d0uz3w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yngf5ztpu6g6da96xdlheheyv5pwuax2g7yale5d4tvwd6y02c7sc8gfm6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYm5UVUF0SmlmTkI5bDU2
            dk0xWTFKOWp6cnhKWFQ5TURmSnlqdmN5VHhJCkx2TkhKRnAxaFViREU5SmVOZnFt
            eEFkQkFxQVZBcllraWFTa3EybklkWG8KLS0tIHROVXdTVG9TaHFUZHhxM21Ja1VD
            YVQ2OVoydEFRY09JS2c2OU1DeGs1WnMKQBbO0NH28dc7l1ZzJrOPjdXLF9//Kh7G
            5j6fQsS+VhqhhCION/V572DjFjVcVlNQe9vKmqlfwiGgiaYlnaKMzA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12r0mh7h98zrn7m0zrzwxm75wr3terzkf6q58nqg64tcul5eyfg0qmgt5lk
    lastmodified: "2026-04-23T14:22:43Z"
    mac: ENC[AES256_GCM,data:ClxsIe72ml4ZMPMU6fwa8XtU3dBFX3YFnH4oJ1yZKoHLZGUx8PbG9nU95rXVnuqnnyyI8HBgZIgWFV4IDWpWvjZcdMJ9z1g2wzXaM6aEPzkEqRfUTL9h1ZDkMr5vWGP8IkA7wtx2WqHr86uc6TNiC2KQ9E61Jz4rPdnh0rGxLNs=,iv:KeXu3ieApO5M8RlqsNKRHhDKRUy7/Q9NHvu+ez/L0rQ=,tag:a1vyWQuQ57Of/o01SpB9jA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.7.3
