apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agones-system

resources:
  - ../../../base/agones

patches:
  - target:
      kind: HelmChart
      name: agones
    patch: |-
      - op: replace
        path: /valuesFile
        value: values-local.yaml