apiVersion: ENC[AES256_GCM,data:DBE=,iv:OsYBKZxRcj/rCKURoitMYoFLEcqj75NRYQk8vryH9xw=,tag:Jv9V0rHt5MPsEzxPl3Swzg==,type:str]
kind: ENC[AES256_GCM,data:eaf4GVc9,iv:GFmGugQk9FigEQfM0zuJp5NeCQSj66DmnmchX08ww5U=,tag:gbwfFuLrSZE6pMWYNz6Naw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:WY395dcbqvi+qER4JrIstQ==,iv:QApT0djO9xZpxY0xY/1wvll7f+fmEiap9EfZVwy7TaM=,tag:/f1XL39eI3KI0WiS4jL3Cg==,type:str]
type: ENC[AES256_GCM,data:Gh8XDtpf,iv:soAg2eZ2LN4fGMnWXPFJtHyuZg5AW6zjLVZ+CapG33M=,tag:Wh5rZZSheOul0OB1TsA1WA==,type:str]
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:eOCHor8X9abAAKpnDLPMmTK4SHoL5XhrORWDTve6zP3Z8gjJt8AsykXWlB9ilPUjN/y+gbS1273fKBxZXpryKg==,iv:epkkrsb0VZ+nQIdGBwJyUYSrKnsNQLLy8uAqZP9G2YI=,tag:xHDILOnYUIE1wvwtpecCSw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:d0waErdpgxAythrJB3bHhuVx8akdkc7HJFhxde7tbjmpCz9PjKEZTlBNAgym2Xz181GBKNTIDFcQ7xuYOUIaRBrKW10+63dUJTc8gEAWHdYP8ZGqDYQ=,iv:7IUsIpVOoqoC2owj7M3cMHlCRH4nxlPAkzJHynW0/d0=,tag:ytTyrYSHgNXJy6mgaOeO+w==,type:str]
    SIDECAR_API_KEY: ENC[AES256_GCM,data:zGq6lAyDyc+OidGg+kleb4I=,iv:jmtxzVJ7LVQI8ybkxy2fzgabA+uqMQPEQGeP7AJz6xM=,tag:O8GlbXJNkR01oWseu3DqXA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xkwx4z6rzmf95xvqnan69agjyvt0lrh0305gzh6p5anndfaee9mqur9933
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5QjE2WWJPOVltcUo5M0lQ
            T1hSUDAvRHdlOENkWGU1ZE9waS9uUFJoZmpBCkx2eXE2MlJ1OHpQQXNyRStmUjZr
            b21KT0xQVTU0bHJSRUszbDlkRDJkQVEKLS0tIEVFTFZVa1RmMFlhUll5RURpWUpm
            emhJajJ3QjJ3dkEySXhreXRVVWJwMzgKzMIzJnW+JkPeS5Hi+bOfg/uP2GCjOJ6i
            FKVrRHblRiiphEsZE4LET4peL67xr0l8tukH5wfvn+usHnmAKErGqg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yngf5ztpu6g6da96xdlheheyv5pwuax2g7yale5d4tvwd6y02c7sc8gfm6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Qi9qZHoxQSs2c1BrMSs1
            bVFTdVN2aEdzR3pDeGhsSDBxT1lkaWNxWHc4CkR1WTEyMlZBNXVwRzhzZklNUlB3
            eG9LNnN4dTlnemdtUitCTmR5MFZ4ZGcKLS0tIHVLMnczdTM4ZTcyRy9NU3Y1M0FZ
            elhTZ2FtMklsWU1aSjZUN0ZxbWc1cTQKlXb8FFDF5Y9emuvZN4BrF4GMeqMQmkBg
            gmhaFe1eRM/9RzVsbLcs5I4TDD943eemr9+tbNBKBaqmixQS3EhWug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T18:27:38Z"
    mac: ENC[AES256_GCM,data:5pW5A5dwNb91JERJIQzf2+ajne/n80Tba8M4M4Ppxtice3PsIKpOh+VkFN5Tbiu8+YaHo33tbpPVQhaT598nWSx+XjjWdrgi4fHzl8sy0Vl1uTpslKyo3zyqKfp3Ry+3WO/uL5bPZN/Qj24Bt2xiZ/2kfnTeJyItAKQ1Ffc3m1E=,iv:UyIbTfD70mjOs8xa32nwXjP+eWLA75NHHcCMVAdTBMQ=,tag:M9CHP4Rpg60rJ0UIp6HM9g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
