apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: craftcloud-system

# 1. Inherit everything from the base folder
resources:
  - identity-secret.plain.yaml
  - fleet-secret.plain.yaml
  - telemetry-secret.plain.yaml
  - postgres-secret.plain.yaml

#generators:
#  - secret-generator.yaml