apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: craftcloud-system

resources:
  - identity-secret.sops.yaml
  - fleet-secret.sops.yaml
  - telemetry-secret.sops.yaml
  - postgres-secret.sops.yaml
  - redis-secret.sops.yaml
  - qdrant-secret.sops.yaml