apiVersion: ENC[AES256_GCM,data:Gvw=,iv:RUUY3sciS+efz4pIJ7SrwY3a4LHVTCQxjPFhprWPDiQ=,tag:lyweq3RLGF53lschD0Q2Vw==,type:str]
kind: ENC[AES256_GCM,data:bOy03T3D,iv:SQrXabg2soGl+OnhVRsuoHIfGzWa1sVWecyysSx2vkQ=,tag:KVqlABMkEWiOyJ6hEEluDw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:vnfffXU5QjWrnH4l1HzZbg==,iv:san2I7yy5vj+8LbTkvkr2JkR5aCDwOwovFu0ogeQ574=,tag:2RcP3G6JjtzNohVsbwGyPA==,type:str]
    namespace: ENC[AES256_GCM,data:xz/2LDGMAzg6GaC9X3FdVJs=,iv:YWYRVwECTN7l/mavftFqdeuIVoQkpuO4zk3BAlYvtnc=,tag:4cwHjR1qqVD/guS2CKlMFA==,type:str]
type: ENC[AES256_GCM,data:PWDR15+T,iv:KDb6lt6UIdnXeJl8L6E1sWe8zNBxrLY3kFB8OP8SpZA=,tag:NpqdWg97fKj4GcFt4XHQLg==,type:str]
stringData:
    DB_PASS: ENC[AES256_GCM,data:Gf0fq4NXBW30CiZiZFIl0K2ZyQK+PsgN7koQ,iv:pZjrmx9/HCOfC0TldUEY4ww2H5DiLHGMdOX8jgIqWbU=,tag:O809kfvla/1EByEe+xzmGw==,type:str]
    SYNCER_DB_PASSWORD: ENC[AES256_GCM,data:W7Bul1Qe2u+AfFTSkgDW8Q==,iv:zAM0xGfFZZOt2dl258ZcmetuID4fxNWAFP564//AnoA=,tag:hq1e/oTZLySK+eicTidVLw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xkwx4z6rzmf95xvqnan69agjyvt0lrh0305gzh6p5anndfaee9mqur9933
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNUkFYc2Y2dVdWeU1TK0xv
            SGN6QkpLVkxQWk0zU1dnbzBHeVpsTGlacm1BCnIzVFEwakNDTjh2SFpOVXhuU1l0
            aDlsektlbzRQT2RrNXVYT0Z3b055WXMKLS0tIDdxVkNPREdwSnU1a2syYmlwNmx2
            UlViOG90L0theUNRYnp4dnpOTThUazQK7hSlzjKXUVdX3bZHf14ULzZsmgJORBav
            vC0RBduoBe9fPX8Fw4jn1RDiwBxjjJPyK37epPsQuzqKNZyEO8LEYA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yngf5ztpu6g6da96xdlheheyv5pwuax2g7yale5d4tvwd6y02c7sc8gfm6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRa2Q1cHdkOWVUemlCR3VK
            MzRCcTQweVpLcUgwVUZCdWkzVnJDT055N2o0Ci9sazBBWVR2WHdZSGFHalh3bWdw
            b2pZNW52UTdsckdIbVRGd1pKWDJOd0kKLS0tIEZKOWJQUkp4MGZ4TUF4YlpYaWxm
            TUJRVUF5Vm91SjZzZEEranFhcU96S0UKTYGWFgx5y0144aDXSqPwdYfCN/Wj98X3
            WQry63HcJOfnSZPp9wwDesluOR2ALW3u5c8eGA2E1ZirF1ZUHZqnow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T19:17:32Z"
    mac: ENC[AES256_GCM,data:T3AT3xWEgM2fWdKbrIPeCL7bhOwq3LU9ld0nLoe4JfUO5prGmiAQINmqEPVoBvRDJ9KtL7sirL5EYcSiD6F4/FWOUp7nRTyPxxMwdlYXeFtGYjExnU/HxEHBOiU7cmWJPHbt+9A+Ohx11J1YnI5sQBFsbiDy908NVrrN3IYSAo0=,iv:axaphXUfN53pSewwojE4osjlDeqcbGLAaI5wJ/H59eE=,tag:2zrSyQjizHG/YPIHTOB4Sg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
