apiVersion: ENC[AES256_GCM,data:+XE=,iv:1fHcEVd8v7PLjQJ4ZMvGQwWWM1pT2Av7A26+S7zEEiY=,tag:MksFNczQyBudW0mDY6Nnsw==,type:str]
kind: ENC[AES256_GCM,data:10DnGUfd,iv:4gekO15x5CHxaVw3DXm58Nwf+9rV89X/7vzTk9o8efg=,tag:92LR4XKI/vILp/Egch7B7w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:IGaOInacKL6nz4w3CIY=,iv:9JT62MCOjAXWOw1+v8Q5EZx544JW8JA+imEu941BvJE=,tag:SSzPX8CcLAQrSGpi2u1k4A==,type:str]
    namespace: ENC[AES256_GCM,data:eBBhL9zOPoplyHCYxfYHQ1Q=,iv:BtEUAoolmTEMMHx+b+IPaHzBTP9HkaUcRZXmFFalz5I=,tag:9opg4vlVGLTDFbEpDlQ5lQ==,type:str]
stringData:
    API_KEY: ENC[AES256_GCM,data:yo4INzZ78yxI3Bo9l2CWPS02kzJtDmZbpHCi,iv:VKtCRjn18XtMMfzue6xTbRtSmIsev2sTqe3bPctuR5g=,tag:US4ZkgVUKVmiKLWividypQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xkwx4z6rzmf95xvqnan69agjyvt0lrh0305gzh6p5anndfaee9mqur9933
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPWkZBSWhqeWZYdGl6MlJm
            Y3IyVHFWVERqWXA3eFZ5cFpNYTdTRWNnam1VCnVkZTZpc1JsaEpvcVVPZ1c1RHVF
            TnpxNUdhWDY0eWpqdDlMeXZGdXRmbGMKLS0tIDBKTnVINFF6Z0pqU1RoRVQ2UEx0
            TWYwQjNPTmZacUYvOUxqOWpqTnhkKzgK7RyiBCZLAq+aPfiR/AcFSJw7u3QrZXTg
            FJ810afrSCq4GDwGwEsm4o7PbNKbLkTQXHs96qpoJAHvGn3ErqpiUQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yngf5ztpu6g6da96xdlheheyv5pwuax2g7yale5d4tvwd6y02c7sc8gfm6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCa1ZiclVicUZRVWUwTzly
            TEpCaTdEUDJDbjIveERFb25nVzRxM0plaWpBClN2a0xYT0J3OXpKcWdvZlpTRndI
            VzlUSGtnSWlud01FSDRUdDZzbVZhRWsKLS0tIE9wTWsxM3dFbm9yOHdZRmVZR29F
            aFhHeU1VYTE1d0hveG1FT1ZSZzM2RUEKA+Zr9IO+SJshOODLWhVeONBS+gbWzIum
            7XZMxzg0316N6/mV8cAuJEE+SM7FP7hQhvutxFI+Axk+01SF1azu+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-23T14:22:43Z"
    mac: ENC[AES256_GCM,data:ClxsIe72ml4ZMPMU6fwa8XtU3dBFX3YFnH4oJ1yZKoHLZGUx8PbG9nU95rXVnuqnnyyI8HBgZIgWFV4IDWpWvjZcdMJ9z1g2wzXaM6aEPzkEqRfUTL9h1ZDkMr5vWGP8IkA7wtx2WqHr86uc6TNiC2KQ9E61Jz4rPdnh0rGxLNs=,iv:KeXu3ieApO5M8RlqsNKRHhDKRUy7/Q9NHvu+ez/L0rQ=,tag:a1vyWQuQ57Of/o01SpB9jA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
