apiVersion: ENC[AES256_GCM,data:PIU=,iv:Ecra9LF2k7d90Xa7EDKP6N7NHX878fYVW8uXxalmFes=,tag:q0S0j97oP9O/3vYHjQNnBw==,type:str]
kind: ENC[AES256_GCM,data:7SYI9xpQ,iv:l2fnIQeNkPR/Rjg1xALLcM2NOYLZk2OaQ/CxPGBphlk=,tag:Iw2MXRYePfUX4O+4uYff6Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:MfvwDpfjzJ8aAqLbcg==,iv:BKlHPATfTGCjYzvp6hu7cMwBnRlmIimwRLPGHSQMAjw=,tag:G2QhDQi2ioPHr5gSVUdEWA==,type:str]
    namespace: ENC[AES256_GCM,data:KytL2NcG1/1pbXugOanNORs=,iv:6spObFlBtSFTKXcWlBgfv4Lfd0CxAR8pKU30Fvuxw4A=,tag:DIkMNzcJ3bYT9jqJzeZA/A==,type:str]
stringData:
    REDIS_PASSWORD: ENC[AES256_GCM,data:gp3PUNnZPNWf+g736gOzz+SiKFWQ1kyVNe9VcQ==,iv:mtrOjhyX0/3mG2VQv+ewoS7vBrJFTlUznjpsQueIpyI=,tag:KafeLmY16elWcs3Jm+qKDQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xkwx4z6rzmf95xvqnan69agjyvt0lrh0305gzh6p5anndfaee9mqur9933
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBScFJaamRuS05KWitjMFVF
            SVlHMHlVWldFL09xc1JmZGdKakRmOHpoampvCk04bi9QTkFmRkhkTHdwaTVWTUN5
            KzY4WFVxTFEvcTY1T1NzN25JWkJLc2cKLS0tIHBvSGVyUEtEM3JFSkM2OHdnb1Rm
            bWtFb2hESVpwS1haOWhFYnVFTmd3M0kKY48RaDuGwP6GFf1Ubw0+Yp8H1GUm9ur7
            SDEbjJ6NxopaXpnm4XTXM/J5Ub7ij1UHSs93G1PJGqhT3HpRxkbhkQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yngf5ztpu6g6da96xdlheheyv5pwuax2g7yale5d4tvwd6y02c7sc8gfm6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Y1RWVUxsaE40a1BmMko1
            QzQ1UUNUUGFIVTZyM3VFd3FUQjd2VW8zc3pjCkJqZTd6cDQxSjBPQitxZHYwK0ZN
            QWFkb0xCa0NkZ3FwRHd0TFp3T1NFUVEKLS0tIDBOWVl3RGNVUWt5aHZFK1U4dkpE
            R1kwRHdNazB6TDJmWjR1dzVmN0xSRDAKv3R2PEPIpdJZMrFnTgdeAKus2kG7mEfC
            u09dg4ZOXyB15Ha1zQRyAIb8sN8QlRsz+pHEMiXRUODw1YbLwN1ruw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-23T14:15:00Z"
    mac: ENC[AES256_GCM,data:jHrMpfVsvcVk67l/tY88+oQnRZYGapLDFfJxliUOGcev00uOVyyN5t1Kw+tNhP+kN2rEmEVwArUl0MrhGPSNvwu+f/8t/KbiDyosSrPBl3nPMMyVGBcgIMjT8JsTCBzMkXqBD1jFbksUZGPdfQMQAeylSqURR1uXD7ejI88sZow=,iv:Qzsph7dnHl2FuJP7oCkZF5Q+QOPpidpdcVDYgiVzvKg=,tag:Wz2tSqQE/8d6jKkTUA33AA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
