apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: dev-microservice-secrets
files:
  - ./identity-secret.sops.yaml
  - ./fleet-secret.sops.yaml
  - ./telemetry-secret.sops.yaml
  - ./postgres-secret.sops.yaml