apiVersion: ENC[AES256_GCM,data:m0M=,iv:NLKZWhdGeVtOJaI4mHQxK1Hbku8BEDlOVKGJfWaegbI=,tag:1L38VDpqTzNZ4qUZC2lxsQ==,type:str]
kind: ENC[AES256_GCM,data:PSSqs/T0,iv:fxQEq3tnnCFdNixxKDjofNnudB9Nl2udoLOhEQmwLXI=,tag:lv9gOmbXUaZjbAq4K8QWWQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ZOv/rcJ+pmyWgDU0uAUmylc=,iv:lMlKetxNFapR6qBK9t+lTjYDn0aBYxmdGDMw6YKx6Ps=,tag:JMTjquiDSOyUk0B0L72o2w==,type:str]
type: ENC[AES256_GCM,data:yaLGTkY2,iv:8/C6nbc4cNuCDnhaftQq/Rk5ltdd4/I2B+MTw2Mgjmo=,tag:aW5UArOaDbjJx336agcO7Q==,type:str]
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:5TuJu0UyqxJij0O52KzvgUr0baYGFblksUFGA8IS/pJ+K22evDQPmAy83rYFN6+iZjsF+k2OMQ8U4ImYXGO7TQ==,iv:LPajD6AMr6hvgI1Mr2ktxNDvDzLlSLCslXx0nQbPzOI=,tag:yhTyJ3O/nE23cT8bBKC4pQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:wdsy6GbXCKXzolxqYFeCwXwXROlI6sJU4ecyjn5crDh9M2yowjdylfirQyDhpJVJ57BPn9Zs3pYR5pG9d0Byujza0otrvnzE/7C2/Ci1,iv:WPGL3uANz73qNdtX61uwcDnLmXGn+AiTaYfdRPe0AWk=,tag:QnTJkcUOmjiQmlCOsVZWmg==,type:str]
    SIDECAR_API_KEY: ENC[AES256_GCM,data:DOn8cD7MWa4PS9nDyjQGLVo=,iv:Tf5Juc5b0hk8dDrNZ8fM66nh+pdwMrYdbnNZRoysPlU=,tag:+QZONiXO32FfIAEuUiEBYg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xkwx4z6rzmf95xvqnan69agjyvt0lrh0305gzh6p5anndfaee9mqur9933
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZlJDN3JjdktUTFQvZE41
            NHZKQlZndGtQQ1Raa0NNNnlqQVpCYytWUUZZCjV6T2lXM0pTOFFka2hWOE1iOHBu
            RmQwVG5lRzhrOVJiRWRpZW9SMWJIZ0EKLS0tIHpqazdrL24rTzk1ZDFtZndJcjhJ
            RDcrZCtBcmJOang0MjBuZkNZMXdGZ1EKbqhWHvdoAozVq7RixuxMkDE/AccCpR8p
            mdffNjQGu33Rdp26w/cuFKJRUPoZYACNxiIzu2RkLLQnoxPx9Kj8Mg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yngf5ztpu6g6da96xdlheheyv5pwuax2g7yale5d4tvwd6y02c7sc8gfm6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArNXFrK0dVT2JKaU90ZzZI
            SE91LzJYdldtSWpLdHZOZy9jTXBYUW9kZFIwCnF0eHNRdG5jeUNRZU5hUlJEcEQ5
            VVVsWlFaOFVZMkF4NHhPSC9jTCtlMkEKLS0tIDJteGtsNXpPc3o0OWhBam1XbUNw
            RFZWWVJraWx6K2VHdFdlUDIwOStvelEKcr59/0SRyHji1G5rpAeY0/yd3D3QbZrr
            G9YW+rRxKk6QNAqijUgBR6tiLb6lX/UzPUMQIvN3bsDc4TMnHyWf7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T21:14:47Z"
    mac: ENC[AES256_GCM,data:2ETGqRbNN6weEeAEDRtPFmX+t+Krk2ayJRyIXlgugYT88ZcumMbBROtYY/MCLFBRaNADBO509i4hb2ZswV1UU61JyeWa9mFCInbBthA8XDaxnVUhzqmo1WgAv86wFe9snykZizF1BnYHGpEtYSzIS9yTHyVNF7tq6gqGwEojems=,iv:cVv/BT9pTRqGGqs4+C7n7FpijCRBnF5AuOQhWUIxp68=,tag:n+tJDs9djMBt7U7EJ2cUmw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
