---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: agones-sdk
  namespace: valheim-workloads
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: agones-sdk
  namespace: valheim-workloads
rules:
  - apiGroups: ["agones.dev"]
    resources: ["gameservers"]
    verbs: ["get", "update", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: agones-sdk
  namespace: valheim-workloads
subjects:
  - kind: ServiceAccount
    name: agones-sdk
    namespace: valheim-workloads
roleRef:
  kind: Role
  name: agones-sdk
  apiGroup: rbac.authorization.k8s.io