apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agones-system
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://agones.dev/chart/stable'
    targetRevision: 1.56.0
    chart: agones
    helm:
      releaseName: agones-system

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: agones-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true