apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-database
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://charts.bitnami.com/bitnami'
      targetRevision: 18.5.x
      chart: postgresql
      helm:
        releaseName: postgres
        valueFiles:
          - $values/infra/values/postgres-values.yaml

    - repoURL: 'https://github.com/jamesmckim/CloudCraft.git'
      targetRevision: main
      ref: values

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: craftcloud-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true