apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qdrant-database
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://qdrant.github.io/qdrant-helm'
    targetRevision: 1.17.x
    chart: qdrant
    helm:
      releaseName: qdrant

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: craftcloud-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true