apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qdrant-database
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://qdrant.github.io/qdrant-helm'
      targetRevision: 1.17.x
      chart: qdrant
      helm:
        releaseName: qdrant
        valueFiles:
          - $values/infra/values/qdrant-values.yaml
    - repoURL: 'https://github.com/jamesmckim/CloudCraft.git'
      targetRevision: main
      ref: values

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: craftcloud-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true