apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-broker
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 25.3.x
    chart: redis
    helm:
      releaseName: redis-broker

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: craftcloud-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true