apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-broker
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://charts.bitnami.com/bitnami'
      targetRevision: 25.3.x
      chart: redis
      helm:
        releaseName: redis-broker
        valueFiles:
          - $values/infra/values/redis-values.yaml
    - repoURL: 'https://github.com/jamesmckim/CloudCraft.git'
      targetRevision: main
      ref: values

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: craftcloud-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true