---
- name: Download K3s installation script
  ansible.builtin.get_url:
    url: https://get.k3s.io
    dest: /tmp/install_k3s.sh
    mode: '0700'

- name: Determine Flannel interface from Ansible Facts
  ansible.builtin.set_fact:
    flannel_iface: "{{ item }}"
  loop: "{{ ansible_interfaces }}"
  when: 
    - vars['ansible_' + item | replace('-', '_')].ipv4 is defined
    - vars['ansible_' + item | replace('-', '_')].ipv4.address == internal_ip
    
- name: Install K3s Control Plane
  ansible.builtin.shell: >
    /tmp/install_k3s.sh server 
    --node-ip="{{ internal_ip }}" 
    --advertise-address="{{ internal_ip }}" 
    --node-name="master-{{ internal_ip }}"
    --flannel-backend="{{ k3s_flannel_backend | default('vxlan') }}"
    --flannel-iface="{{ flannel_iface }}"
  environment:
    K3S_TOKEN: "{{ k3s_cluster_token }}"
  args:
    creates: /etc/rancher/k3s/k3s.yaml
  # 'creates' ensures this only runs once. If the yaml exists, Ansible skips this task.

- name: Wait for K3s API port to become available
  ansible.builtin.wait_for:
    port: 6443
    state: started
    timeout: 300
    msg: "Timeout waiting for K3s API to come online."

- name: Patch CoreDNS to use public DNS (Fix Ubuntu 22.04 Loopback Bug)
  ansible.builtin.shell: |
    /usr/local/bin/kubectl get configmap coredns -n kube-system -o yaml | sed 's/forward . \/etc\/resolv.conf/forward . 8.8.8.8 1.1.1.1/g' | /usr/local/bin/kubectl apply -f -
    /usr/local/bin/kubectl rollout restart deployment coredns -n kube-system
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  register: coredns_patch
  changed_when: "'configured' in coredns_patch.stdout"