---
- name: Download K3s installation script
  ansible.builtin.get_url:
    url: https://get.k3s.io
    dest: /tmp/install_k3s.sh
    mode: '0700'

- name: Determine Flannel interface from Ansible Facts
  ansible.builtin.set_fact:
    flannel_iface: "{{ item }}"
  loop: "{{ ansible_interfaces }}"
  when: 
    - vars['ansible_' + item | replace('-', '_')].ipv4 is defined
    - vars['ansible_' + item | replace('-', '_')].ipv4.address == internal_ip

- name: Ensure K3s configuration directory exists
  ansible.builtin.file:
    path: /etc/rancher/k3s
    state: directory
    mode: '0755'
  become: yes

- name: Create custom upstream DNS configuration (Bypass Ubuntu Loopback)
  ansible.builtin.copy:
    dest: /etc/rancher/k3s/custom-resolv.conf
    content: |
      nameserver 8.8.8.8
      nameserver 1.1.1.1
    mode: '0644'
  become: yes

- name: Install K3s Control Plane
  ansible.builtin.shell: >
    /tmp/install_k3s.sh server 
    --node-ip="{{ internal_ip }}" 
    --advertise-address="{{ internal_ip }}" 
    --node-name="master-{{ internal_ip }}"
    --flannel-backend="{{ k3s_flannel_backend | default('vxlan') }}"
    --flannel-iface="{{ flannel_iface }}"
    --flannel-conf='{"Network": "10.42.0.0/16", "Backend": {"Type": "vxlan", "VNI": 1, "Port": 8472}, "MTU": 1150}'
    --resolv-conf="/etc/rancher/k3s/custom-resolv.conf"
  environment:
    K3S_TOKEN: "{{ k3s_cluster_token }}"
  args:
    creates: /etc/rancher/k3s/k3s.yaml
  # 'creates' ensures this only runs once. If the yaml exists, Ansible skips this task.

- name: Wait for K3s API port to become available
  ansible.builtin.wait_for:
    port: 6443
    state: started
    timeout: 300
    msg: "Timeout waiting for K3s API to come online."