apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agones-system

helmCharts:
  - name: agones
    repo: https://agones.dev/chart/stable
    version: 1.56.0
    releaseName: agones-system
    namespace: agones-system
    valuesFile: values/agones-values.yaml