apiVersion: v1
kind: Service
metadata:
  name: telemetry-service
  namespace: craftcloud-system
spec:
  selector:
    app: telemetry-service
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http