apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agones-system
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/jamesmckim/CloudCraft.git'
      targetRevision: main
      path: deployments/k8s/overlays/base/agones

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: agones-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true