apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agones-system
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://agones.dev/chart/stable'
      targetRevision: 1.56.0
      chart: agones
      helm:
        releaseName: agones-system
        valueFiles:
          - $values/infra/values/agones-values.yaml 
    - repoURL: 'https://github.com/jamesmckim/CloudCraft.git'
      targetRevision: main
      ref: values

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: agones-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true