apiVersion: v1
kind: Namespace
metadata:
  name: agones-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: craftcloud-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: prometheus-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"