apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/jamesmckim/CloudCraft.git'
      targetRevision: main
      path: deployments/k8s/overlays/dev/prometheus
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prometheus-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true