apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: public-gateway
  namespace: craftcloud-system
  labels:
    app: craftcloud
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    # Apply API stripping AND Header stripping
    traefik.ingress.kubernetes.io/router.middlewares: craftcloud-system-strip-api@kubernetescrd, craftcloud-system-strip-external-user-id@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - "app.127.0.0.1.nip.io"
      secretName: sso-tls
  rules:
    - host: "app.127.0.0.1.nip.io"
      http:
        paths:
          # --- Public Auth Routes (Register, Token) ---
          - path: /api/auth
            pathType: Prefix
            backend:
              service:
                name: identity-service
                port:
                  number: 5000

          # --- Public Webhook Routes ---
          - path: /api/payments/webhook
            pathType: Prefix
            backend:
              service:
                name: identity-service
                port:
                  number: 5000

          # --- Dashboard Route ---
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dashboard
                port:
                  number: 80