apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-domains
data:
  BASE_DOMAIN: "127.0.0.1.nip.io:8443"
  SSO_AUTHORITY: "https://sso.127.0.0.1.nip.io:8443/realms/craftcloud"
  API_GATEWAY_URL: "https://api.127.0.0.1.nip.io:8443"
  WEBUI_URL: "https://app.127.0.0.1.nip.io:8443"