apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: craftcloud-system

resources:
  - postgres-cluster.yaml
  - ../dev-shared/

generators:
  - ksops-generator.yaml

helmCharts:
  - name: redis
    repo: https://charts.bitnami.com/bitnami
    version: 25.3.12
    releaseName: redis-broker
    namespace: craftcloud-system
    valuesFile: ../../../../infra/values/redis-values.yaml

  - name: qdrant
    repo: https://qdrant.github.io/qdrant-helm
    version: 1.18.0
    releaseName: qdrant
    namespace: craftcloud-system
    valuesFile: ../../../../infra/values/qdrant-values.yaml