apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres-cluster.yaml
  - ../dev-shared/
  - cluster-domains.yaml
  - webui-runtime-config.yaml

generators:
  - ksops-generator.yaml

replacements:
  - source:
      kind: ConfigMap
      name: cluster-domains
      fieldPath: data.SSO_AUTHORITY
    targets:
      - select:
          kind: ConfigMap
          name: webui-runtime-config
        fieldPaths:
          - data.[config.js]
        options:
          delimiter: '"'
          index: 1

  - source:
      kind: ConfigMap
      name: cluster-domains
      fieldPath: data.API_GATEWAY_URL
    targets:
      - select:
          kind: ConfigMap
          name: webui-runtime-config
        fieldPaths:
          - data.[config.js]
        options:
          delimiter: '"'
          index: 5

helmCharts:
  - name: redis
    repo: oci://registry-1.docker.io/bitnamicharts
    version: 25.3.12
    releaseName: redis-broker
    namespace: craftcloud-system
    valuesFile: values/redis-values.yaml

  - name: qdrant
    repo: https://qdrant.github.io/qdrant-helm
    version: 1.18.0
    releaseName: qdrant
    namespace: craftcloud-system
    valuesFile: values/qdrant-values.yaml