apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-gateway
  labels:
    app: craftcloud
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: craftcloud-system-strip-api@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: "localhost"
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: manager-api
                port:
                  number: 5000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dashboard
                port:
                  number: 80