---
# 0. Lay the Foundation
- name: Base OS and Networking Setup
  hosts: all
  become: yes
  roles:
    - common

# 1. Setup the Brain (Control Plane)
- name: Bootstrap K3s Control Plane
  hosts: master
  become: yes
  any_errors_fatal: true
  roles:
    - k3s_master

# 2. Attach the Limbs (Workers)
- name: Bootstrap K3s Workers
  hosts: workers
  become: yes
  roles:
    - k3s_worker

# 3. Deploy the Software (GitOps & Game Servers)
- name: Deploy Cluster Applications
  hosts: master
  become: yes
  gather_facts: false
  roles:
    - argocd