---
- name: Ensure Python Kubernetes client is installed natively on the Master
  ansible.builtin.apt:
    name: python3-kubernetes
    state: present
    update_cache: yes
    
- name: Ensure ArgoCD namespace exists
  kubernetes.core.k8s:
    name: argocd
    kind: Namespace
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present

- name: Apply ArgoCD Core Manifests
  kubernetes.core.k8s:
    src: https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
    namespace: argocd
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present

- name: Wait for ArgoCD Server to become Available
  kubernetes.core.k8s_info:
    kind: Deployment
    name: argocd-server
    namespace: argocd
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    wait: yes
    wait_condition:
      type: Available
      status: "True"
    wait_timeout: 300

- name: Wait for ArgoCD Application Controller to become Available
  kubernetes.core.k8s_info:
    kind: Deployment
    name: argocd-application-controller
    namespace: argocd
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    wait: yes
    wait_condition:
      type: Available
      status: "True"
    wait_timeout: 300

- name: Apply GitOps Application Manifest
  kubernetes.core.k8s:
    src: https://raw.githubusercontent.com/jamesmckim/CloudCraft/main/infra/master-infra-app.yaml
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present