apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - infra/agones-sdk/rbac-sdk.yaml
  - config/
  - data/redis/
  - frontend/dashboard/
  - workers/mod-syncer/
  - workers/ai-rag-worker/
  - workers/payment-worker/
  - services/

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: sidecar-scripts
    namespace: valheim-workloads
    files:
      - main.py=infra/sidecar-scripts/main.py
      - probes.py=infra/sidecar-scripts/probes.py
    