---
- name: Extract Master Internal IP
  ansible.builtin.set_fact:
    master_ip: "{{ hostvars[groups['master'][0]]['internal_ip'] }}"

- name: Wait for Control Plane to open port 6443
  ansible.builtin.wait_for:
    host: "{{ master_ip }}"
    port: 6443
    state: started
    timeout: 300
    msg: "Worker timed out waiting for the Control Plane ({{ master_ip }}) to become ready."

- name: Download K3s installation script
  ansible.builtin.get_url:
    url: https://get.k3s.io
    dest: /tmp/install_k3s_agent.sh
    mode: '0700'

- name: Determine Flannel interface from Ansible Facts
  ansible.builtin.set_fact:
    flannel_iface: "{{ item }}"
  loop: "{{ ansible_interfaces }}"
  when: 
    - vars['ansible_' + item | replace('-', '_')].ipv4 is defined
    - vars['ansible_' + item | replace('-', '_')].ipv4.address == internal_ip

- name: Ensure K3s configuration directory exists
  ansible.builtin.file:
    path: /etc/rancher/k3s
    state: directory
    mode: '0755'
  become: yes

- name: Create custom upstream DNS configuration (Bypass Ubuntu Loopback)
  ansible.builtin.copy:
    dest: /etc/rancher/k3s/custom-resolv.conf
    content: |
      nameserver 8.8.8.8
      nameserver 1.1.1.1
    mode: '0644'
  become: yes

- name: Join K3s cluster as Worker (This is apparetnly important)
  ansible.builtin.shell: >
    /tmp/install_k3s_agent.sh agent
    --node-ip="{{ internal_ip }}"
    --node-name="worker-{{ internal_ip }}"
    --flannel-iface="{{ flannel_iface }}"
    --resolv-conf="/etc/rancher/k3s/custom-resolv.conf"
  environment:
    K3S_URL: "https://{{ master_ip }}:6443"
    K3S_TOKEN: "{{ k3s_cluster_token }}"
  args:
    creates: /etc/rancher/k3s/k3s-agent.env
  # 'creates' ensures idempotency: skips if the agent config already exists

- name: Ensure K3s agent is started and enabled
  ansible.builtin.systemd:
    name: k3s-agent
    state: started
    enabled: yes