apiVersion: ENC[AES256_GCM,data:Dh0=,iv:FrhP2ngVfyymhetIdqpuSXhDXm6DpKFn91LTZd9xANk=,tag:BodB3glUukVEHuW/0nrOZw==,type:str]
kind: ENC[AES256_GCM,data:6IbH0CG7,iv:pYxNx1ertY89rlzhu9Val3JY8pSWoYIjIU6qjBhNRZE=,tag:AyDmD9bA+BLXodTYQpGdXw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:r8u8aTR35xFhvggm9w==,iv:utF2QGxr3qr+o/RWDdn9I1mZyOUbQTbJ9XOmwiDJjyE=,tag:MLrK5VbxF5FPk6MOCmVyiA==,type:str]
type: ENC[AES256_GCM,data:HuhbGTGs,iv:oW4Agtpb4iBZGFxvOs40CmGBmU6oh4b8zZVWT55j3I0=,tag:dGdPdqYzi8PSBIUtD+x3MA==,type:str]
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:gn5wjqjDj4GtdsG0dvipWr/15+itTSimYgZA9I7o5+y5YhDQsmk2/1SReb3Jfjqwdq+Ngxv/eQXSe0w5hzXnag==,iv:TFRsyYneruYhn66DCubTc+BCPHmDXMvpehbCfKGL/rI=,tag:6XFgWOVuGL9jxQCfJNXREQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:T+G8law0zXH4FiY2VxXrBUI+z9BPgTweHXhLHhyn7ZP9uRMbvhHLTIg+kzCsBQ+LnT+Er7v0MEdaGsmq+EYMPXiU8cJBzkEF2X3W/vPx,iv:7gX5zRcZCM9KoEzM2UDBnRUWEtPqT8Z/7b9/OXn45jI=,tag:c5HyE3ZsioiJME7oxuSaPg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xkwx4z6rzmf95xvqnan69agjyvt0lrh0305gzh6p5anndfaee9mqur9933
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4UEJrTUcyYWxvdUpzUHoy
            K0U4Sll1UHd4K2xYbmZpL3psSWhJWnhDeVE4CmNNZmhWY0FvaDFhRnJpcnRScGZV
            M2Y3eXNDODBuRUFtR1N0SEI0aGFKT28KLS0tIGlXRkVUaUFQZ3o4d2MySUtqNUdu
            eHNMMGNzVHEwRDhHMVFFSXJjMktrNm8KvCcZyhpMey3kErrxL9CCj54brK7TcXTy
            LestoUKEyiTQQYFXlYgr6FFjff7nHkuTF56LwOb61wXYYxpTfrV+lA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T19:50:04Z"
    mac: ENC[AES256_GCM,data:QpWpmiyQTLyHO9ihEI7IsmQ3hedHwbm98v8Z3vZqwLnBr043D7jTWtRwsEwkKCMA4yni4R/AdVvaXxmc9g8mmNMMD0/2bcnB/srDjNKiZ3cXG1oOvwonXTpUD6kURjFAhaMy3nB2T9/02UrLVbs8q+gKRrPitLhDIz88UsT+9DI=,iv:4fU2J4twNvRbKROv0Uh/0Szw/4rm/q1hgg28w1MhrgU=,tag:30nwWseSktjRAb89nbDlGQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
