apiVersion: ENC[AES256_GCM,data:Gvw=,iv:RUUY3sciS+efz4pIJ7SrwY3a4LHVTCQxjPFhprWPDiQ=,tag:lyweq3RLGF53lschD0Q2Vw==,type:str]
kind: ENC[AES256_GCM,data:bOy03T3D,iv:SQrXabg2soGl+OnhVRsuoHIfGzWa1sVWecyysSx2vkQ=,tag:KVqlABMkEWiOyJ6hEEluDw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:vnfffXU5QjWrnH4l1HzZbg==,iv:san2I7yy5vj+8LbTkvkr2JkR5aCDwOwovFu0ogeQ574=,tag:2RcP3G6JjtzNohVsbwGyPA==,type:str]
type: ENC[AES256_GCM,data:PWDR15+T,iv:KDb6lt6UIdnXeJl8L6E1sWe8zNBxrLY3kFB8OP8SpZA=,tag:NpqdWg97fKj4GcFt4XHQLg==,type:str]
stringData:
    DB_PASS: ENC[AES256_GCM,data:Gf0fq4NXBW30CiZiZFIl0K2ZyQK+PsgN7koQ,iv:pZjrmx9/HCOfC0TldUEY4ww2H5DiLHGMdOX8jgIqWbU=,tag:O809kfvla/1EByEe+xzmGw==,type:str]
    SYNCER_DB_PASSWORD: ENC[AES256_GCM,data:W7Bul1Qe2u+AfFTSkgDW8Q==,iv:zAM0xGfFZZOt2dl258ZcmetuID4fxNWAFP564//AnoA=,tag:hq1e/oTZLySK+eicTidVLw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xkwx4z6rzmf95xvqnan69agjyvt0lrh0305gzh6p5anndfaee9mqur9933
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwYStqK3dRT3JzaXNyUTBu
            Z1pYalF6SStkTEpRWnZsenJLVWlhRlVOaTNVCjR1bHpnREppN1dOTnpBSlltK1NY
            cFFFaDVXQjFObmIzcWYra0pEVGFSblEKLS0tIEd5VXV4S1FvNmpCRWdWOCtjVEx0
            TTVLdG1qUUQ1YitXSHBNTlVTTkg4UGcKlICqfu+FCY4nRNDgndaF2iHBGaxlA862
            zoWeqvJZgXhGJeWfma8tqHlCUcuIHJSjoIO6D5OQRRqaOFEFRs1IHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T20:20:21Z"
    mac: ENC[AES256_GCM,data:sZPLpRFJWOXeux2DkbYf9Am3WAgMiqm8J8eFZs5d+U9CmJ269n4JsUduKQlcVlaUQinb040ph0QRphB5doRL1qcnLQqt/ZXcW7zI5MqoWJoKO0dMM2fasuuBai5P85ptsACNKy+8swwP5cnlskGi5NJy5KKz3nyUnZbIQQH7dYU=,iv:YerkT2zU0OPwSKw7UsNQCuvV5c4FavsYm8CSLXiwojM=,tag:BvEzc9pzQQaGHVOp9ALa7w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
