apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
  namespace: craftcloud-system
  labels:
    app: identity-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-service
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      containers:
        - name: identity-service
          image: identity-api-image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
              name: http
          env:
            - name: ENVIRONMENT
              value: "development"
            - name : DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: identity-secrets
                  key: DATABASE_URL
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: identity-secrets
                  key: SECRET_KEY
            - name: INTERNAL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: identity-secrets
                  key: INTERNAL_API_KEY
      initContainers:
        - name: wait-for-db
          image: postgres:18-alpine
          env:
            - name: PGHOST
              value: "postgres"
            - name: PGUSER
              value: "user"
          command:
            - sh
            - -c
            - |
              echo "Waiting for database..."
              until pg_isready; do
                sleep 2
              done
              echo "Database is ready!"