apiVersion: ENC[AES256_GCM,data:UxQ=,iv:e2QW86JOatseZ5p4+Jgq83OtDo6ETdgfhnuu82zcSJw=,tag:KORWOYM2GzkJQX9Tf7J5Zg==,type:str]
kind: ENC[AES256_GCM,data:ys8lDeaP,iv:XK7Z37c7OLVhuE3lT8idtIXzE9RFZ9rVE/XOTrUFmS4=,tag:0LITXkMt3B1DXYQfXnyoHw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:LHNzfgNG4vhXlwBZ0aCH9QsN,iv:gMgm3IKXQBIxleFgjCBbmfY3mjmDTmeDYdRSuS9y0BA=,tag:Tz7rjsaHGIyZYUlNiRs++Q==,type:str]
    namespace: ENC[AES256_GCM,data:6sqOyxbvl115Crgid7hGrDA=,iv:hs6FLxu87VQX2ClXBxigVjX7h29/K45vHXkPHsMaOQo=,tag:7qmSncBQiRdf1qLvf0uQCw==,type:str]
type: ENC[AES256_GCM,data:PjUqLWja,iv:zgtf5i+GGGCqYlDkHxpSnC8Hm7VuMLGIPDsIoLKXZsk=,tag:cQ2xs06NESf3gLxBEZm9KA==,type:str]
stringData:
    username: ENC[AES256_GCM,data:GMnvYw==,iv:iIp4ioEL9Hm9dDMpi4Txx8JBS6xtbQK7F0Fye/ull08=,tag:ZOx8X1QDq1nbsJs2kbI/MQ==,type:str]
    password: ENC[AES256_GCM,data:QCSyDq3GwQKS1DhiS91OU8jDiBkDm85KKN9y,iv:AeyAqtl3Dwr2syyGaKiOf3R/hUOu9hPQaMAiY269WVA=,tag:abIeeRgxTztD8e0H6FQDQg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xkwx4z6rzmf95xvqnan69agjyvt0lrh0305gzh6p5anndfaee9mqur9933
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCTWhDWE5PTHcyUjlrTVZT
            cWplMmh2Z29CR2xGM0d0ZnltNFV6M2tzbngwCnk1QTh0QmZITmZ5YU1JRHFMTXVw
            SjhUbmU2bUVHM2Y0Y0txdEVZa1VDakUKLS0tIFJnZExUaWVTYW9Bb2l5TGxnMXlX
            ZjJGa1ArUWRzR01DSlltMGFla0lHVG8KWnt8ouSQVmTt5ZYgNdTAqpFVUGFpb6jH
            VcYY2ltrYai+kJbq0aUexivkw5BqrLZDM7rvaumTTXbm4wJWYgK9mw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yngf5ztpu6g6da96xdlheheyv5pwuax2g7yale5d4tvwd6y02c7sc8gfm6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNMHBtUkpTQ1poNmJBZmdZ
            d2Z3b3BiUWVzb3VZQlh6aW53RjhvTWtZZUVNCklrSnVvNTIzQ2pVYW9FZGE1ZmlM
            ZFFWT29RV0JnMlhURlVtSHU3dllhTUUKLS0tIFJIZ3IvV1FQTFNkUFJyTG1VZzFm
            eEo0UnpXSHpMU1FCQnpnVnI2dDhMd2MKBUmqIxgeAacM6dNemg7Mjc6N8DbQHU55
            6AnOJn56uOnoAu2CZ2Eh1q3Add3+OlmdgAYDRqK2DfxsGSnNcCLdDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-10T15:06:32Z"
    mac: ENC[AES256_GCM,data:zmaL1AWensWk3VHfHgoQj33fXn/g0niBAPg/3S95fFf+HQnkY0wDtPbwE4apAbb2QSj5B5B6exg3kYzwwsUCcSDqUNSFwiTeLtjTTszHFJqk6ActxL1eJFipkXr2OJ4q62J9h5pCwJKVjhJysPUImgQjMKHm4yX/HwNeIE4L5sA=,iv:RkaMgK8AtZUl2s0RBhFKlJzn8cRcR9Z11pRKy6GXQ7g=,tag:E1cDp5C252xbqvxkUdudcw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
