apiVersion: ENC[AES256_GCM,data:Njk=,iv:PuSEPRoFoHQBzcdsaB9Jvv4uafNTDcigmKEYHB7M4/k=,tag:O5RyKS9zriC59v3HGGXg3A==,type:str]
kind: ENC[AES256_GCM,data:5PFx8BkX,iv:3cpkvAZoNHWWIHJguWqDgFYrgrIDVyXcj0GpTTQfnMw=,tag:nHntZFUHpQPiTerUqV7Iog==,type:str]
metadata:
    name: ENC[AES256_GCM,data:DcUS/JbAPtLpGMGgIGklCu4y,iv:FEj6YT3ecn59x9uM+sLW10PoJsZk64J1528502OJBqU=,tag:ujIknWIEnUfdCdpiqaf3xg==,type:str]
    namespace: ENC[AES256_GCM,data:f880IcC9UL2WLd0gnjRrdxs=,iv:dAgowuvQXrkM60rBeFOkTl7qcrpkDhJaXTTWalQ90GM=,tag:c/h4RKZJOHR9HXhKUcqDTg==,type:str]
type: ENC[AES256_GCM,data:H+tVB7UW,iv:dn0zSDO70EzSIghOg1BueI/V3r6k+8/On7U0ParV/D0=,tag:oFWUcgJqh2Zj2vZA/cfbMQ==,type:str]
stringData:
    username: ENC[AES256_GCM,data:NGZAMryrv3A=,iv:H2ZA08NdET5TZr3/exq0bdWTlShtnPp+rh3Q8A0dXno=,tag:OV5Bmb4hY0SDoNNzF5FyMA==,type:str]
    password: ENC[AES256_GCM,data:bwKZ7vah2PNCai5gcECYwa57ZF4erCVju6f1,iv:7HqO/LO63bbdT73eKxpPw0mfz5DvSNQwH7A8+IqnIeg=,tag:SWxdt8MoFRVSyR8xnUGTXQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtQmRWb2ROVmlyZzNZU0V5
            bHh2TGZURzFORjlEZXN0UVVMeDNvR1FuU3dzCnl6U3pnUUZ2QnNlTWxYK2F0VVAr
            cGhydm5IRGs3dXFaY0tUcG9NSkNhcmcKLS0tIGVwd054T2lUcUd3ODdhbDVBY1VV
            WWZnZkwzUGh2VDBPSjVwc3h2Ynh5T2MKD02KpnwkCFWlUhm4NbtkVfBlBUoeUYJo
            2C3gV7N+Ze5LiBngOj7Uk18722MscRYgEfTXvwaxWHD0OxQyLncdkQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xkwx4z6rzmf95xvqnan69agjyvt0lrh0305gzh6p5anndfaee9mqur9933
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHY3d3S2ZyRDZnaHpTa0dI
            Qkcra0tGbnVnTXYxL3lJWTZsc25HTzY3TmxFCmI1T3QrTnlwMzN0VG03OXNnbi9B
            aFJobDZJMndYeVljdU9lbjJ4ZFd6RWsKLS0tIFdDY0tmbFdSRk4vNVJSSi9iaDkv
            ZmtaM05PRFhXenRCb0hib2Rxa0N3NHcKfEvx+sCBhY080iFYlWgLjuhIJD/mP9C2
            oISrMQv6MpF4xFV+P3woHrKmemYYgY9twXZtABy+oEu6aMzSBNEukw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yngf5ztpu6g6da96xdlheheyv5pwuax2g7yale5d4tvwd6y02c7sc8gfm6
    lastmodified: "2026-07-09T18:45:02Z"
    mac: ENC[AES256_GCM,data:15Wd0A5ExkGJ+1JhriMcjS4a7D1jnMjrY1az2K0yyzKkoncog/Jja8ctopc8XaY/NvXA9n2iMkjoZNG46NYVjXG8TBbdQx23gmMwoeHHQ890Yrx+oVVJsVEOZPBdHYvyOvRqFPwJ753XNHC0MwtAv3Ov5Rp3BlNvOEwBkQGzwP8=,iv:VAHtkvFEUs1NSOgSby/2gVeDlUph1OuBaU9kEvTyr1A=,tag:tajKFIRsu+i3CL13a5ySPg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
