apiVersion: ENC[AES256_GCM,data:Gvw=,iv:RUUY3sciS+efz4pIJ7SrwY3a4LHVTCQxjPFhprWPDiQ=,tag:lyweq3RLGF53lschD0Q2Vw==,type:str]
kind: ENC[AES256_GCM,data:bOy03T3D,iv:SQrXabg2soGl+OnhVRsuoHIfGzWa1sVWecyysSx2vkQ=,tag:KVqlABMkEWiOyJ6hEEluDw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:vnfffXU5QjWrnH4l1HzZbg==,iv:san2I7yy5vj+8LbTkvkr2JkR5aCDwOwovFu0ogeQ574=,tag:2RcP3G6JjtzNohVsbwGyPA==,type:str]
    namespace: ENC[AES256_GCM,data:xz/2LDGMAzg6GaC9X3FdVJs=,iv:YWYRVwECTN7l/mavftFqdeuIVoQkpuO4zk3BAlYvtnc=,tag:4cwHjR1qqVD/guS2CKlMFA==,type:str]
type: ENC[AES256_GCM,data:PWDR15+T,iv:KDb6lt6UIdnXeJl8L6E1sWe8zNBxrLY3kFB8OP8SpZA=,tag:NpqdWg97fKj4GcFt4XHQLg==,type:str]
stringData:
    DB_PASS: ENC[AES256_GCM,data:Gf0fq4NXBW30CiZiZFIl0K2ZyQK+PsgN7koQ,iv:pZjrmx9/HCOfC0TldUEY4ww2H5DiLHGMdOX8jgIqWbU=,tag:O809kfvla/1EByEe+xzmGw==,type:str]
    ADMIN_PASS: ENC[AES256_GCM,data:hdzufOd8kxaM+snRx7L2E2wrs6m2MWKc84Fodw==,iv:JGsxJVKluAoMSZaZvNsDu8SHVH3SLT0urTgONGJrZC8=,tag:/P0dHNh2zjKm+1KkwnJFsg==,type:str]
    SYNCER_DB_PASSWORD: ENC[AES256_GCM,data:W7Bul1Qe2u+AfFTSkgDW8Q==,iv:zAM0xGfFZZOt2dl258ZcmetuID4fxNWAFP564//AnoA=,tag:hq1e/oTZLySK+eicTidVLw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwbUw0MDJIWVR2d2lPMk5r
            VS83bVl3dy9FZy9sWDdnTUxzMnJwNTZad1ZNCnphVUJuNjJzNW1QWjJyNy90QkR4
            UndHMXF2UFNUQ01yZk5PLy9kZER5c1UKLS0tIE1QbWxDWG5OUi9rN3B6cmZUZ0Na
            cnE2Y3FPRHNHS2l3S2ptdGRpV25sUVEKC7+F2fp8d6E7EELxD4pRFJyc9dZqbgSB
            9bn8PHBVmEBDl4jXLoapEEbNZsZDG1jLuvpAm2EH4GZ/ymv1TyLJjQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yngf5ztpu6g6da96xdlheheyv5pwuax2g7yale5d4tvwd6y02c7sc8gfm6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRM2h2RHlYek84TW5FeGMw
            d3RDZVNFYVNhSHYvQlBsZzh5ZHFGcXpaTnhzCkJES2paRkhDbzg5b2wwSFUxTm5j
            WGtoSWNJMTdzZVJrc3ZFWTI4L1NPdEkKLS0tIHlCNTRsMWlPd2VPUXRHV2JqTG9K
            TVQ1TGZsYjY1V0NpU0NUSlZrdTJ5YTQKinl1emao0A8cj7GTCpS2ofd58EOt4XRr
            YgNwMEWl6HNjO4/y65gTxNzuXdzU1cae4wo+Dlzvhzje+e+y2nBycQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12r0mh7h98zrn7m0zrzwxm75wr3terzkf6q58nqg64tcul5eyfg0qmgt5lk
    lastmodified: "2026-04-23T15:23:08Z"
    mac: ENC[AES256_GCM,data:03YWH4gna4yTBQeycCAGL1LJa3xT9CQ0blun0ms/zRRcMJpYXZYFZQx2ucEgHIItx8NlAvC2bKNj7uuWGH72Vh0AnI6GrpisqH8AjuMVut2cYDWoIIqyeFNF7+yjFy4NkuhqTbOJ7nKgKsweIqEvzlwqc+J+C/G9mYbp9DxKLhQ=,iv:XI6rx0WDUnXIDIDfp0GKrxVrf10g7JJqOjWAH0wx95M=,tag:YjgjAwVbQk/6pyrr5ed6jQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.7.3
