apiVersion: ENC[AES256_GCM,data:PIU=,iv:Ecra9LF2k7d90Xa7EDKP6N7NHX878fYVW8uXxalmFes=,tag:q0S0j97oP9O/3vYHjQNnBw==,type:str]
kind: ENC[AES256_GCM,data:7SYI9xpQ,iv:l2fnIQeNkPR/Rjg1xALLcM2NOYLZk2OaQ/CxPGBphlk=,tag:Iw2MXRYePfUX4O+4uYff6Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:MfvwDpfjzJ8aAqLbcg==,iv:BKlHPATfTGCjYzvp6hu7cMwBnRlmIimwRLPGHSQMAjw=,tag:G2QhDQi2ioPHr5gSVUdEWA==,type:str]
    namespace: ENC[AES256_GCM,data:KytL2NcG1/1pbXugOanNORs=,iv:6spObFlBtSFTKXcWlBgfv4Lfd0CxAR8pKU30Fvuxw4A=,tag:DIkMNzcJ3bYT9jqJzeZA/A==,type:str]
stringData:
    REDIS_PASSWORD: ENC[AES256_GCM,data:gp3PUNnZPNWf+g736gOzz+SiKFWQ1kyVNe9VcQ==,iv:mtrOjhyX0/3mG2VQv+ewoS7vBrJFTlUznjpsQueIpyI=,tag:KafeLmY16elWcs3Jm+qKDQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvTHVFQVo1d0lpUzFJV2pt
            UnF4MXYyOXZvVVFlZ3hyaFk5NTJFZmNnK21RCmVDTCtlblhvODJVRHVzdks2QWdO
            SHlOem9LeXB6QndmbXluUjVRK3dITGsKLS0tIEVYNkxqT2Nod0gwT1FQQjZMUlJX
            Y3ZlZ0JQRlpmd3NIUWdqTjNRampzemsKAwq09iGLjjclXo6VrsWFlQ8XXQVmZjsA
            v/sCp2iewvv6Wrn7p34MsDKTTHN6YMDRnND5Ojl+/VnQuBNe+zNl/w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yngf5ztpu6g6da96xdlheheyv5pwuax2g7yale5d4tvwd6y02c7sc8gfm6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRRE93MEJtTmlYaUFxVll4
            ZVpFc1Z6bnJZRXI5eHJvN01CLzc0cFBMVFNjCkNPWDNaRGlKMVhueE5rQnVlMWla
            dXBhVUZMS3llWG5LOUpSSkVDT3FzdEkKLS0tIFdwWEYzY0JXQnd0MlBkTklicVMv
            cXB5b2xsVlQ2N2F2Vld3MzJwdzdmT00KTvyIt7brj36VznbIY6dwMW6omiOWfYv7
            F4exHUlnZjWn29RBeqWWf6toN4I3yYAd3ABfc+AUwhdBpi0qO0yeTQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12r0mh7h98zrn7m0zrzwxm75wr3terzkf6q58nqg64tcul5eyfg0qmgt5lk
    lastmodified: "2026-04-23T14:15:00Z"
    mac: ENC[AES256_GCM,data:jHrMpfVsvcVk67l/tY88+oQnRZYGapLDFfJxliUOGcev00uOVyyN5t1Kw+tNhP+kN2rEmEVwArUl0MrhGPSNvwu+f/8t/KbiDyosSrPBl3nPMMyVGBcgIMjT8JsTCBzMkXqBD1jFbksUZGPdfQMQAeylSqURR1uXD7ejI88sZow=,iv:Qzsph7dnHl2FuJP7oCkZF5Q+QOPpidpdcVDYgiVzvKg=,tag:Wz2tSqQE/8d6jKkTUA33AA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.7.3
